_BASE_: "Base-RCNN-FPN.yaml"
OUTPUT_DIR: sign-detector-lowtopk
MODEL:
  WEIGHTS: None
  MASK_ON: False
  RPN:
    NMS_THRESH: 0.3
    POST_NMS_TOPK_TRAIN: 200
    POST_NMS_TOPK_TEST: 100
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 512
    NUM_CLASSES: 1
    SCORE_THRESH_TEST: 0.3
    NMS_THRESH_TEST: 0.2
    POSITIVE_FRACTION: 0.25
DATASETS:
  TRAIN: ("hotspots_train",)
  TEST: ("hotspots_val",)
TEST: 
  EVAL_PERIOD: 500
INPUT:
  RANDOM_FLIP: "none"
DATALOADER:
  NUM_WORKERS: 1
SOLVER: 
  IMS_PER_BATCH: 5
  BASE_LR: 0.0003
  MAX_ITER: 100000
