_BASE_: "Base-RCNN-FPN.yaml"
OUTPUT_DIR: traindirs/sign-detector-shallow-newdata
MODEL:
  WEIGHTS: None
  MASK_ON: False
  RPN:
    NMS_THRESH: 0.3 
    POST_NMS_TOPK_TRAIN: 200
    POST_NMS_TOPK_TEST: 100
  RESNETS:
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 512
    NUM_CLASSES: 1
    SCORE_THRESH_TEST: 0.3
    NMS_THRESH_TEST: 0.2
    POSITIVE_FRACTION: 0.25
DATASETS:
  TRAIN: ("hotspots_new_train",)
  TEST: ("hotspots_new_val",)
TEST: 
  EVAL_PERIOD: 100
INPUT:
  RANDOM_FLIP: "none"
DATALOADER:
  NUM_WORKERS: 1
SOLVER: 
  IMS_PER_BATCH: 15
  BASE_LR: 0.003
  STEPS: (10000, 20000)
  MAX_ITER: 30000
